### PR TITLE
fix: distance func to static for success isolate run

### PR DESCRIPTION
**Pull request by AbdullahChauhan**

### CODE REVIEW

**Comment by AbdullahChauhan** [comment]
@JankoLancer Can you take a look at this?

**Comment by JankoLancer** [comment]
@AbdullahChauhan  Sorry for the delay. Can you please explain to me how this enables isolate run?

**Comment by AbdullahChauhan** [comment]
> @AbdullahChauhan Sorry for the delay.

No problem. 

> Can you please explain to me how this enables isolate run?

This is my top-level function:
`GeocodeData _geocode(String data) {
  return GeocodeData(data, 'name', 'country code', 'latitude', 'longitude',
      fieldDelimiter: '\t', eol: '\n');
}`

And this is how I'm calling the function inside my `class` function:
`final result = await compute(_geocode, data);`

But this gives me the common isolate error:
`Unhandled Exception: Exception: Invalid argument(s): Illegal argument in isolate message : (object is a closure - Function '_distance@77005115':.)`

So when I dig into package code, I found out the`_distance` function (mention in the above error) is neither static nor top-level function so for a successful isolate run I change this function to static and it's working fine. 

P.S. I'm working all this offline geocoding in isolate because it's not blocking the UI thread since the file containing geocoding data is too big.

**Comment by AbdullahChauhan** [comment]
> > @AbdullahChauhan Sorry for the delay.
> 
> No problem.
> 
> > Can you please explain to me how this enables isolate run?
> 
> This is my top-level function:
> `GeocodeData _geocode(String data) { return GeocodeData(data, 'name', 'country code', 'latitude', 'longitude', fieldDelimiter: '\t', eol: '\n'); }`
> 
> And this is how I'm calling the function inside my `class` function:
> `final result = await compute(_geocode, data);`
> 
> But this gives me the common isolate error:
> `Unhandled Exception: Exception: Invalid argument(s): Illegal argument in isolate message : (object is a closure - Function '_distance@77005115':.)`
> 
> So when I dig into package code, I found out the`_distance` function (mention in the above error) is neither static nor top-level function so for a successful isolate run I change this function to static and it's working fine.
> 
> P.S. I'm working all this offline geocoding in isolate because it's not blocking the UI thread since the file containing geocoding data is too big.

@JankoLancer

**Pull request merged**
